from typing import Protocol
from uuid import UUID
class ApprovalGateway(Protocol):
    async def request(self,action:str,target:str,reason:str,risk_level:str)->UUID: ...
    async def approve(self,approval_id:UUID)->None: ...
    async def reject(self,approval_id:UUID)->None: ...
