from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0002_phase2_intelligence"; down_revision="0001_phase1_foundation"; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("intelligence_runs",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("project_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("projects.id",ondelete="SET NULL")),sa.Column("task_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("tasks.id",ondelete="SET NULL")),sa.Column("request",sa.Text(),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("current_stage",sa.String(40),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("estimated_cost",sa.Float()),sa.Column("actual_cost",sa.Float()),sa.Column("result",postgresql.JSONB(),nullable=False),sa.Column("error",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False))
    op.create_index("ix_intelligence_runs_project_id","intelligence_runs",["project_id"]); op.create_index("ix_intelligence_runs_task_id","intelligence_runs",["task_id"]); op.create_index("ix_intelligence_runs_status","intelligence_runs",["status"])
    op.create_table("research_findings",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("intelligence_run_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("intelligence_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("query",sa.Text(),nullable=False),sa.Column("title",sa.String(500),nullable=False),sa.Column("url",sa.Text()),sa.Column("source",sa.String(300)),sa.Column("evidence",sa.Text(),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("provider",sa.String(80),nullable=False),sa.Column("metadata",postgresql.JSONB(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False)); op.create_index("ix_research_findings_intelligence_run_id","research_findings",["intelligence_run_id"])
    op.create_table("task_plans",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("intelligence_run_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("intelligence_runs.id",ondelete="CASCADE"),nullable=False,unique=True),sa.Column("plan",postgresql.JSONB(),nullable=False)); op.create_index("ix_task_plans_intelligence_run_id","task_plans",["intelligence_run_id"])
    op.create_table("specialist_briefs",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("intelligence_run_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("intelligence_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("specialist",sa.String(120),nullable=False),sa.Column("brief",postgresql.JSONB(),nullable=False)); op.create_index("ix_specialist_briefs_intelligence_run_id","specialist_briefs",["intelligence_run_id"])
    op.create_table("prompt_artifacts",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("intelligence_run_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("intelligence_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("specialist",sa.String(120)),sa.Column("prompt",postgresql.JSONB(),nullable=False),sa.Column("critique",postgresql.JSONB(),nullable=False)); op.create_index("ix_prompt_artifacts_intelligence_run_id","prompt_artifacts",["intelligence_run_id"])
    op.create_table("model_invocations",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("intelligence_run_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("intelligence_runs.id",ondelete="CASCADE"),nullable=False),sa.Column("provider",sa.String(80),nullable=False),sa.Column("model",sa.String(160),nullable=False),sa.Column("input_tokens",sa.Integer(),nullable=False),sa.Column("output_tokens",sa.Integer(),nullable=False),sa.Column("latency_ms",sa.Float()),sa.Column("estimated_cost",sa.Float()),sa.Column("actual_cost",sa.Float()),sa.Column("metadata",postgresql.JSONB(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False)); op.create_index("ix_model_invocations_intelligence_run_id","model_invocations",["intelligence_run_id"])

def downgrade():
    op.drop_index("ix_model_invocations_intelligence_run_id",table_name="model_invocations"); op.drop_table("model_invocations"); op.drop_index("ix_prompt_artifacts_intelligence_run_id",table_name="prompt_artifacts"); op.drop_table("prompt_artifacts"); op.drop_index("ix_specialist_briefs_intelligence_run_id",table_name="specialist_briefs"); op.drop_table("specialist_briefs"); op.drop_index("ix_task_plans_intelligence_run_id",table_name="task_plans"); op.drop_table("task_plans"); op.drop_index("ix_research_findings_intelligence_run_id",table_name="research_findings"); op.drop_table("research_findings"); op.drop_index("ix_intelligence_runs_status",table_name="intelligence_runs"); op.drop_index("ix_intelligence_runs_task_id",table_name="intelligence_runs"); op.drop_index("ix_intelligence_runs_project_id",table_name="intelligence_runs"); op.drop_table("intelligence_runs")
