from dataclasses import dataclass
from enum import StrEnum
from typing import Any,Protocol
from uuid import UUID
class EventType(StrEnum):
    PROJECT_CREATED="PROJECT_CREATED"; PROJECT_UPDATED="PROJECT_UPDATED"; TASK_CREATED="TASK_CREATED"; TASK_STARTED="TASK_STARTED"; TASK_COMPLETED="TASK_COMPLETED"; TASK_FAILED="TASK_FAILED"; APPROVAL_REQUESTED="APPROVAL_REQUESTED"; APPROVAL_GRANTED="APPROVAL_GRANTED"; APPROVAL_REJECTED="APPROVAL_REJECTED"; WORKFLOW_STARTED="WORKFLOW_STARTED"; WORKFLOW_COMPLETED="WORKFLOW_COMPLETED"; WORKFLOW_FAILED="WORKFLOW_FAILED"; INTELLIGENCE_RUN_CREATED="INTELLIGENCE_RUN_CREATED"; INTELLIGENCE_RUN_STARTED="INTELLIGENCE_RUN_STARTED"; INTELLIGENCE_STAGE_STARTED="INTELLIGENCE_STAGE_STARTED"; INTELLIGENCE_STAGE_COMPLETED="INTELLIGENCE_STAGE_COMPLETED"; INTELLIGENCE_STAGE_FAILED="INTELLIGENCE_STAGE_FAILED"; RESEARCH_COMPLETED="RESEARCH_COMPLETED"; PLAN_CREATED="PLAN_CREATED"; SPECIALISTS_SELECTED="SPECIALISTS_SELECTED"; BRIEF_CREATED="BRIEF_CREATED"; PROMPT_CREATED="PROMPT_CREATED"; PROMPT_OPTIMIZED="PROMPT_OPTIMIZED"; MODEL_ROUTED="MODEL_ROUTED"; MODEL_EXECUTED="MODEL_EXECUTED"; MODEL_EXECUTION_FAILED="MODEL_EXECUTION_FAILED"; INTELLIGENCE_RUN_COMPLETED="INTELLIGENCE_RUN_COMPLETED"; INTELLIGENCE_RUN_FAILED="INTELLIGENCE_RUN_FAILED"
@dataclass(frozen=True)
class Job: id:UUID; type:str; payload:dict[str,Any]; priority:int=0; attempt:int=0; metadata:dict[str,Any]|None=None
class JobHandler(Protocol):
    async def handle(self,job:Job)->None: ...
class JobQueue(Protocol):
    async def enqueue(self,job:Job)->None: ...
    async def dequeue(self,timeout:int=5)->Job|None: ...
class Agent(Protocol):
    name:str; capabilities:tuple[str,...]
    async def execute(self,context:dict[str,Any])->dict[str,Any]: ...
class ModelProvider(Protocol):
    name:str
    async def complete(self,request:dict[str,Any])->dict[str,Any]: ...
class ModelRouter(Protocol):
    async def route(self,request:dict[str,Any])->dict[str,Any]: ...
class CostRouter(Protocol):
    async def estimate(self,request:dict[str,Any])->dict[str,Any]: ...
@dataclass(frozen=True)
class TaskIntelligence:
    goal:str; context:str; requirements:tuple[str,...]; constraints:tuple[str,...]; audience:str|None; deliverables:tuple[str,...]; dependencies:tuple[str,...]; risks:tuple[str,...]; success_criteria:tuple[str,...]; research_findings:tuple[str,...]; recommended_specialists:tuple[str,...]
@dataclass(frozen=True)
class SpecialistBrief:
    objective:str; task_research:str; requirements:tuple[str,...]; constraints:tuple[str,...]; audience:str|None; available_tools:tuple[str,...]; project_context:str|None; memory_context:str|None; brand_guidelines:str|None; output_schema:dict[str,Any]; quality_criteria:tuple[str,...]; failure_conditions:tuple[str,...]
class IntentAnalyzer(Protocol):
    async def analyze(self,request:str)->dict[str,Any]: ...
class TaskResearcher(Protocol):
    async def research(self,request:str)->dict[str,Any]: ...
class TaskIntelligenceBuilder(Protocol):
    async def build(self,request:str)->TaskIntelligence: ...
class TaskDecomposer(Protocol):
    async def decompose(self,intelligence:TaskIntelligence)->list[dict[str,Any]]: ...
class SpecialistSelector(Protocol):
    async def select(self,intelligence:TaskIntelligence)->list[str]: ...
class SpecialistResearcher(Protocol):
    async def research(self,specialist:str,intelligence:TaskIntelligence)->dict[str,Any]: ...
class SpecialistBriefBuilder(Protocol):
    async def build(self,intelligence:TaskIntelligence,specialist:str)->SpecialistBrief: ...
class PromptGenerator(Protocol):
    async def generate(self,brief:SpecialistBrief)->dict[str,Any]: ...
class PromptCritic(Protocol):
    async def critique(self,prompt:dict[str,Any])->dict[str,Any]: ...
class PromptOptimizer(Protocol):
    async def optimize(self,prompt:dict[str,Any],critique:dict[str,Any])->dict[str,Any]: ...
class ContextAssembler(Protocol):
    async def assemble(self,request:dict[str,Any])->dict[str,Any]: ...
@dataclass(frozen=True)
class ModelUsage:
    provider:str; model:str; input_tokens:int=0; output_tokens:int=0; latency_ms:float|None=None; estimated_cost:float|None=None; actual_cost:float|None=None; quality_score:float|None=None
