from typing import Any,Protocol
class WorkflowEngine(Protocol):
    async def start(self,workflow:dict[str,Any])->str: ...
    async def cancel(self,workflow_id:str)->None: ...
    async def get(self,workflow_id:str)->dict[str,Any]|None: ...
